# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gm.proto',
  package='PrivateProto',
  syntax='proto2',
  serialized_pb=_b('\n\x08gm.proto\x12\x0cPrivateProto\"\x13\n\x04Ping\x12\x0b\n\x03msg\x18\x01 \x02(\t\"\x13\n\x04Pong\x12\x0b\n\x03msg\x18\x02 \x02(\t\"\x10\n\x0eLoadGameConfig')
)




_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='PrivateProto.Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='PrivateProto.Ping.msg', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=45,
)


_PONG = _descriptor.Descriptor(
  name='Pong',
  full_name='PrivateProto.Pong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='PrivateProto.Pong.msg', index=0,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=66,
)


_LOADGAMECONFIG = _descriptor.Descriptor(
  name='LoadGameConfig',
  full_name='PrivateProto.LoadGameConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.message_types_by_name['Pong'] = _PONG
DESCRIPTOR.message_types_by_name['LoadGameConfig'] = _LOADGAMECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), dict(
  DESCRIPTOR = _PING,
  __module__ = 'gm_pb2'
  # @@protoc_insertion_point(class_scope:PrivateProto.Ping)
  ))
_sym_db.RegisterMessage(Ping)

Pong = _reflection.GeneratedProtocolMessageType('Pong', (_message.Message,), dict(
  DESCRIPTOR = _PONG,
  __module__ = 'gm_pb2'
  # @@protoc_insertion_point(class_scope:PrivateProto.Pong)
  ))
_sym_db.RegisterMessage(Pong)

LoadGameConfig = _reflection.GeneratedProtocolMessageType('LoadGameConfig', (_message.Message,), dict(
  DESCRIPTOR = _LOADGAMECONFIG,
  __module__ = 'gm_pb2'
  # @@protoc_insertion_point(class_scope:PrivateProto.LoadGameConfig)
  ))
_sym_db.RegisterMessage(LoadGameConfig)


# @@protoc_insertion_point(module_scope)
