# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='login.proto',
  package='PrivateProto',
  syntax='proto2',
  serialized_pb=_b('\n\x0blogin.proto\x12\x0cPrivateProto\"\x85\x01\n\nLoginQuest\x12\x10\n\x08verified\x18\x01 \x02(\x08\x12\x0e\n\x06openid\x18\x02 \x02(\t\x12\r\n\x05token\x18\x03 \x02(\t\x12\x0c\n\x04\x63\x63id\x18\x04 \x02(\x04\x12\x0c\n\x04name\x18\x05 \x02(\t\x12\x0e\n\x06imgurl\x18\x06 \x02(\t\x12\r\n\x05ipstr\x18\x07 \x02(\t\x12\x0b\n\x03sex\x18\x08 \x02(\r\"\x8d\x01\n\rRetLoginQuest\x12\x10\n\x08ret_code\x18\x01 \x02(\r\x12\x0c\n\x04\x63\x63id\x18\x02 \x02(\x04\x12\x0c\n\x04\x63uid\x18\x03 \x01(\x04\x12\x0e\n\x06openid\x18\x04 \x01(\t\x12\x0e\n\x06roomid\x18\x05 \x02(\r\x12\x11\n\tnick_name\x18\x06 \x01(\t\x12\x0e\n\x06imgurl\x18\x07 \x01(\t\x12\x0b\n\x03sex\x18\x08 \x01(\r\">\n\x10\x43lientBeReplaced\x12\x0c\n\x04\x63\x63id\x18\x01 \x02(\x03\x12\x0c\n\x04\x63uid\x18\x02 \x02(\x03\x12\x0e\n\x06openid\x18\x03 \x02(\t\"\"\n\x12\x43lientDisconnected\x12\x0c\n\x04\x63\x63id\x18\x01 \x02(\x03*a\n\x15RetLoginQuest_RetCode\x12\x12\n\x0eRLQ_REG_FAILED\x10\x00\x12\x0e\n\nRLQ_SUCCES\x10\x01\x12\x0c\n\x08RLQ_BAND\x10\x02\x12\x16\n\x12RLQ_TOKEN_EXPIRIED\x10\x04')
)

_RETLOGINQUEST_RETCODE = _descriptor.EnumDescriptor(
  name='RetLoginQuest_RetCode',
  full_name='PrivateProto.RetLoginQuest_RetCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RLQ_REG_FAILED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RLQ_SUCCES', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RLQ_BAND', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RLQ_TOKEN_EXPIRIED', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=409,
  serialized_end=506,
)
_sym_db.RegisterEnumDescriptor(_RETLOGINQUEST_RETCODE)

RetLoginQuest_RetCode = enum_type_wrapper.EnumTypeWrapper(_RETLOGINQUEST_RETCODE)
RLQ_REG_FAILED = 0
RLQ_SUCCES = 1
RLQ_BAND = 2
RLQ_TOKEN_EXPIRIED = 4



_LOGINQUEST = _descriptor.Descriptor(
  name='LoginQuest',
  full_name='PrivateProto.LoginQuest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='verified', full_name='PrivateProto.LoginQuest.verified', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='openid', full_name='PrivateProto.LoginQuest.openid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='PrivateProto.LoginQuest.token', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ccid', full_name='PrivateProto.LoginQuest.ccid', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='PrivateProto.LoginQuest.name', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imgurl', full_name='PrivateProto.LoginQuest.imgurl', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ipstr', full_name='PrivateProto.LoginQuest.ipstr', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sex', full_name='PrivateProto.LoginQuest.sex', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=163,
)


_RETLOGINQUEST = _descriptor.Descriptor(
  name='RetLoginQuest',
  full_name='PrivateProto.RetLoginQuest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret_code', full_name='PrivateProto.RetLoginQuest.ret_code', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ccid', full_name='PrivateProto.RetLoginQuest.ccid', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cuid', full_name='PrivateProto.RetLoginQuest.cuid', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='openid', full_name='PrivateProto.RetLoginQuest.openid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roomid', full_name='PrivateProto.RetLoginQuest.roomid', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nick_name', full_name='PrivateProto.RetLoginQuest.nick_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imgurl', full_name='PrivateProto.RetLoginQuest.imgurl', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sex', full_name='PrivateProto.RetLoginQuest.sex', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=307,
)


_CLIENTBEREPLACED = _descriptor.Descriptor(
  name='ClientBeReplaced',
  full_name='PrivateProto.ClientBeReplaced',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ccid', full_name='PrivateProto.ClientBeReplaced.ccid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cuid', full_name='PrivateProto.ClientBeReplaced.cuid', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='openid', full_name='PrivateProto.ClientBeReplaced.openid', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=371,
)


_CLIENTDISCONNECTED = _descriptor.Descriptor(
  name='ClientDisconnected',
  full_name='PrivateProto.ClientDisconnected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ccid', full_name='PrivateProto.ClientDisconnected.ccid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=407,
)

DESCRIPTOR.message_types_by_name['LoginQuest'] = _LOGINQUEST
DESCRIPTOR.message_types_by_name['RetLoginQuest'] = _RETLOGINQUEST
DESCRIPTOR.message_types_by_name['ClientBeReplaced'] = _CLIENTBEREPLACED
DESCRIPTOR.message_types_by_name['ClientDisconnected'] = _CLIENTDISCONNECTED
DESCRIPTOR.enum_types_by_name['RetLoginQuest_RetCode'] = _RETLOGINQUEST_RETCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginQuest = _reflection.GeneratedProtocolMessageType('LoginQuest', (_message.Message,), dict(
  DESCRIPTOR = _LOGINQUEST,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:PrivateProto.LoginQuest)
  ))
_sym_db.RegisterMessage(LoginQuest)

RetLoginQuest = _reflection.GeneratedProtocolMessageType('RetLoginQuest', (_message.Message,), dict(
  DESCRIPTOR = _RETLOGINQUEST,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:PrivateProto.RetLoginQuest)
  ))
_sym_db.RegisterMessage(RetLoginQuest)

ClientBeReplaced = _reflection.GeneratedProtocolMessageType('ClientBeReplaced', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTBEREPLACED,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:PrivateProto.ClientBeReplaced)
  ))
_sym_db.RegisterMessage(ClientBeReplaced)

ClientDisconnected = _reflection.GeneratedProtocolMessageType('ClientDisconnected', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTDISCONNECTED,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:PrivateProto.ClientDisconnected)
  ))
_sym_db.RegisterMessage(ClientDisconnected)


# @@protoc_insertion_point(module_scope)
